import * as yup from 'yup';

export const branchProfileSchema = yup.object({
  branchName: yup.string().trim().required('Branch Name is required'),
  branchCode: yup.string().trim().required('Branch Code is required'),
  branchNo: yup.string().trim().required('Branch No. is required'),
  address1: yup.string().trim().required('Address 1 is required'),
  address2: yup.string().trim().notRequired(),
  address3: yup.string().trim().notRequired(),
  city: yup.string().trim().required('City is required'),
  stateId: yup.string().trim().required('State is required'),
  stdCode: yup.string().trim().notRequired(),
  pinCode: yup.string().trim().notRequired(),
  operationalGroupId: yup
    .string()
    .trim()
    .required('Operational Group is required'),
  phoneNo1CountryCode: yup.string().trim().required(),
  phoneNo1: yup.string().trim().notRequired(),
  phoneNo2CountryCode: yup.string().trim().required(),
  phoneNo2: yup.string().trim().notRequired(),
  faxNo1CountryCode: yup.string().trim().required(),
  faxNo1: yup.string().trim().notRequired(),
  faxNo2CountryCode: yup.string().trim().required(),
  faxNo2: yup.string().trim().notRequired(),
  emailId: yup.string().trim().email('Enter a valid email').notRequired(),
  contactPerson: yup.string().trim().notRequired(),
  contactNoCountryCode: yup.string().trim().required(),
  contactNo: yup.string().trim().notRequired(),
  locationTypeId: yup.string().trim().required('Location Type is required'),
  operationalUserId: yup.string().trim().notRequired(),
  acUserInchargeId: yup.string().trim().notRequired(),
  aiiNo: yup.string().trim().notRequired(),
  wuAiiNo: yup.string().trim().notRequired(),
  rbiLicenceNo: yup.string().trim().notRequired(),
  rbiRegDate: yup.string().trim().notRequired(),
  authSignatory: yup.string().trim().notRequired(),
  branchAttachedToId: yup.string().trim().notRequired(),
  wuAcBranchPostingId: yup.string().trim().notRequired(),
  cashLimit: yup.string().trim().notRequired(),
  ibmHo1: yup.string().trim().notRequired(),
  ibmHo2: yup.string().trim().notRequired(),
  ibmBranchId: yup.string().trim().notRequired(),
  lastSettlementRef: yup.string().trim().notRequired(),
  currencyLimit: yup.string().trim().notRequired(),
  tempCashLimit: yup.string().trim().notRequired(),
  tempCurrencyLimit: yup.string().trim().notRequired(),
  branchHasShifts: yup.boolean().required(),
  canReferenceOnBehalfEntries: yup.boolean().required(),
  serviceTaxApplicable: yup.boolean().required(),
  serviceTaxRegnNo: yup.string().when('serviceTaxApplicable', {
    is: true,
    then: schema => schema.trim().required('Service Tax Regn No. is required'),
    otherwise: schema => schema.trim().notRequired(),
  }),
});
