import { useMemo, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { yupResolver } from '@hookform/resolvers/yup';
import { Form, FormFieldTextarea } from '@/components/forms';
import { Button, Modal } from '@/components/ui';
import { Loader } from '@/components/ui/loader';
import { useListBranchProfiles } from '@/modules/branchProfile/hooks';
import { useAuth } from '@/lib/AuthContext';
import { getTransactionDatePolicy } from '@/modules/transactionPolicies/utils/transactionDatePolicy';
import toast from 'react-hot-toast';
import { CardTransferForm } from '../forms';
import { cardTransferSchema } from '../schema';
import { useAcceptCardTransfer, useCancelCardTransfer, useDeleteCardTransfer, useGetCardTransfer, useRejectCardTransfer, useUpdateCardTransfer } from '../hooks';
import type { CardTransferFormValues } from '../types';

export const CardTransferEditView = () => {
  const navigate = useNavigate();
  const { id = '' } = useParams();
  const { policyContext } = useAuth();
  const { data: request, isLoading, error } = useGetCardTransfer(id);
  const { data: branches = [] } = useListBranchProfiles({ activeOnly: true });
  const [rejectOpen, setRejectOpen] = useState(false);
  const [remarks, setRemarks] = useState('');
  const updateMutation = useUpdateCardTransfer();
  const acceptMutation = useAcceptCardTransfer();
  const rejectMutation = useRejectCardTransfer();
  const cancelMutation = useCancelCardTransfer();
  const deleteMutation = useDeleteCardTransfer();
  const readOnly = request?.status !== 'HELD';
  const initialValues = useMemo(() => request, [request]);
  const policy = useMemo(() => getTransactionDatePolicy(policyContext), [policyContext]);
  if (isLoading) return <Loader />;
  if (error || !request || !initialValues) return <div className="rounded border border-red-300 bg-red-50 p-4 text-sm text-red-700">{error instanceof Error ? error.message : 'CARD transfer request not found.'}</div>;
  const run = async (action: Promise<unknown>, message: string) => { await action; toast.success(message); navigate('/card-transfer'); };
  const save = (values: CardTransferFormValues) => run(updateMutation.mutateAsync({ id, values }), 'CARD transfer request updated.');
  const reject = () => { if (!remarks.trim()) { toast.error('Rejection reason is required.'); return; } void run(rejectMutation.mutateAsync({ id, remarks: remarks.trim() }), 'CARD transfer request rejected.'); };
  const cancel = () => { if (!remarks.trim()) { toast.error('Cancellation reason is required.'); return; } void run(cancelMutation.mutateAsync({ id, remarks: remarks.trim() }), 'CARD transfer request cancelled.'); };
  return <Form<CardTransferFormValues> id="card-transfer-edit-form" defaultValues={initialValues} resolver={yupResolver(cardTransferSchema) as never} mode="onChange" onSubmit={save} footer={{ showSubmit: !readOnly, submitLabel: 'Save CARD Transfer', onCancel: () => navigate('/card-transfer'), actions: <div className="flex flex-wrap gap-2">{request.status === 'HELD' ? <><Button type="button" variant="outline" onClick={() => setRejectOpen(true)}>Reject</Button><Button type="button" variant="outline" onClick={() => setRejectOpen(true)}>Cancel Request</Button><Button type="button" variant="outline" onClick={() => void run(deleteMutation.mutateAsync(id), 'CARD transfer request deleted.')}>Delete</Button><Button type="button" onClick={() => void run(acceptMutation.mutateAsync(id), 'CARD transfer request accepted.')}>Accept</Button></> : null}</div> }}><div className="space-y-4"><div><h1 className="text-2xl font-semibold text-text-primary">{readOnly ? 'CARD Transfer Request' : 'Edit CARD Transfer Sell'}</h1><p className="text-sm text-text-secondary">{readOnly ? `This request is ${request.status.toLowerCase()} and is read-only.` : 'Held requests can be edited or submitted for approval.'}</p></div><CardTransferForm branches={branches} readOnly={readOnly} transactionDatePolicy={policy} /></div><Modal open={rejectOpen} onOpenChange={setRejectOpen} title="Update CARD Transfer Request" description="Enter a reason and choose the action." footer={<div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => setRejectOpen(false)}>Close</Button><Button type="button" variant="outline" onClick={reject}>Reject</Button><Button type="button" onClick={cancel}>Cancel Request</Button></div>}><FormFieldTextarea name="actionRemarks" label="Reason" value={remarks} onChange={event => setRemarks(event.target.value)} placeholder="Enter reason" rows={4} /></Modal></Form>;
};

export default CardTransferEditView;
