export interface IOtherTransactionFormValues {
  transactionType: string;
  profileType: string;
  branchId: string;
  counterId: string;
  dealId: string;
  docNo: string;
  transactionDate: string;
  marketingId: string;
  segmentId: string;
  servicedById: string;
  servicedBy: string;
  purposeId: string;
  remitterName: string;
  contactNo: string;
  email: string;
  address: string;
  pan: string;
  dateOfBirth: string;
  productId: string;
  beneficiaryName: string;
  beniAddress: string;
  beneAccountNumber: string;
  beneBankName: string;
  swiftCode: string;
  relationshipId: string;
  currencyId: string;
  fcVolume: string;
  saleRate: string;
  totalInrAmt: string;
  gst: string;
  bankCharges: string;
  tcs: string;
  otherIncome: string;
  finalAmount: string;
  settlementRate: string;
  grossRevenue: string;
  revenueReceivable: string;
  agentId: string;
  commGiven: string;
  commPercentOnFe: string;
  agentComm: string;
  tds: string;
  commissionPayable: string;
  netRevenue: string;
  bankNameId: string;
  rtgsImpsNeftRefNo: string;
  remarks: string;
}

export const createEmptyOtherTransactionFormValues = (
  overrides: Partial<IOtherTransactionFormValues> = {}
): IOtherTransactionFormValues => ({
  transactionType: '',
  profileType: '',
  branchId: '',
  counterId: '',
  dealId: '',
  docNo: '',
  transactionDate: '',
  marketingId: '',
  segmentId: '',
  servicedById: '',
  servicedBy: '',
  purposeId: '',
  remitterName: '',
  contactNo: '',
  email: '',
  address: '',
  pan: '',
  dateOfBirth: '',
  productId: '',
  beneficiaryName: '',
  beniAddress: '',
  beneAccountNumber: '',
  beneBankName: '',
  swiftCode: '',
  relationshipId: '',
  currencyId: '',
  fcVolume: '',
  saleRate: '',
  totalInrAmt: '',
  gst: '0',
  bankCharges: '0',
  tcs: '0',
  otherIncome: '0',
  finalAmount: '',
  settlementRate: '',
  grossRevenue: '',
  revenueReceivable: '0',
  agentId: '',
  commGiven: '',
  commPercentOnFe: '0',
  agentComm: '0',
  tds: '0',
  commissionPayable: '',
  netRevenue: '',
  bankNameId: '',
  rtgsImpsNeftRefNo: '',
  remarks: '',
  ...overrides,
});
