export const AD1_PRINT_TEXT = {
  heading: 'Print Copy',
  originalHint: 'Print the original copy for this AD1 transaction.',
  duplicateHint: 'Print the duplicate copy for this AD1 transaction.',
  printCopy: 'Print Copy',
  preparing: 'Preparing Print...',
  printed: (label: string) => `${label} sent to printer`,
  printFailed: 'Failed to print AD1 copy',
  popupBlocked: 'Unable to open print window. Please allow pop-ups and try again.',
  title: 'AD1 TRANSACTION',
  originalCopy: 'Original Copy',
  duplicateCopy: 'Duplicate Copy',
  companyBranch: 'Company & Branch Information',
  remitter: 'Remitter Details',
  beneficiary: 'Beneficiary Details',
  pricing: 'Pricing & Settlement',
  agent: 'Agent Commissions',
  bank: 'Bank & Settlement Reference',
  branchGst: 'Branch GST',
  invoiceNo: 'Doc No',
  invoiceDate: 'Date',
  rbiLicNo: 'RBI Lic No',
  panNo: 'PAN No',
  address: 'Address',
  contact: 'Contact',
  email: 'Email',
  name: 'Name',
  pan: 'PAN',
  dateOfBirth: 'Date of Birth',
  dealId: 'Deal ID',
  purpose: 'Purpose',
  product: 'Product',
  currency: 'Currency',
  fcVolume: 'FC Volume',
  saleRate: 'Sale Rate',
  totalInr: 'Total INR',
  gst: 'GST',
  bankCharges: 'Bank Charges',
  tcs: 'TCS',
  otherIncome: 'Other Income',
  finalAmount: 'Final Amount',
  settlementRate: 'Settlement Rate',
  grossRevenue: 'Gross Revenue',
  agentName: 'Agent',
  agentComm: 'Agent Commission',
  tds: 'TDS',
  commissionPayable: 'Commission Payable',
  netRevenue: 'Net Revenue',
  bankName: 'Bank',
  rtgsRef: 'RTGS/IMPS/NEFT Ref',
  beneficiaryName: 'Beneficiary',
  accountNumber: 'Account Number',
  swiftCode: 'SWIFT Code',
  remarks: 'Remarks',
} as const;
