import { DealCoverStatus } from '@/api/dealCoverRate';

export const TT_PRODUCT_CODE = 'TT';

export const DEAL_COVER_RATE_TEXT = {
  title: 'Deal Cover Rate',
  description: 'Create and manage TT deal cover rates pending acknowledgement.',
  empty: 'No deal cover rates found.',
  createTitle: 'Create Deal Cover Rate',
  createDescription:
    'Capture deal details. Deal rate is locked from the product sale margin.',
  editTitle: 'Edit Deal Cover Rate',
  viewTitle: 'Deal Cover Rate',
  readonlyDescription: 'Only PENDING deals can be edited or cancelled.',
  newDeal: 'New Deal Cover Rate',
  submit: 'Save Deal',
  update: 'Update Deal',
  cancel: 'Cancel Deal',
  back: 'Back',
  close: 'Close',
  confirm: 'Confirm',
  view: 'View',
  edit: 'Edit',
  created: 'Deal cover rate created.',
  updated: 'Deal cover rate updated.',
  cancelled: 'Deal cover rate cancelled.',
  notFound: 'Deal cover rate not found.',
  cancelConfirm: 'Cancel this pending deal cover rate?',
  detailsHeading: 'Deal Details',
  passengerHeading: 'Passenger',
  branch: 'Branch',
  selectBranch: 'Select branch',
  transactionDate: 'Transaction Date',
  bankAccount: 'Bank Account',
  selectBank: 'Select bank ledger account',
  product: 'Product',
  selectProduct: 'Select product',
  partyType: 'Party Type',
  selectPartyType: 'Select party type',
  party: 'Party Profile',
  selectParty: 'Select party profile',
  marketingExecutive: 'Marketing Executive',
  selectMarketingExecutive: 'Select marketing executive',
  purpose: 'Purpose',
  subpurpose: 'Subpurpose',
  selectSubpurpose: 'Select subpurpose',
  currency: 'Currency',
  selectCurrency: 'Select currency',
  issuer: 'Issuer',
  selectIssuer: 'Select issuer',
  feAmount: 'FE Amount',
  dealRate: 'Deal Rate',
  inrAmount: 'INR Amount',
  fbChargeAmount: 'FB Charge Amount',
  narration: 'Narration',
  maturity: 'Maturity',
  selectMaturity: 'Select maturity',
  passengerName: 'Passenger Name',
  passengerPan: 'PAN',
  passengerPanHolder: 'PAN Holder',
  passengerPanDob: 'PAN DOB',
  passengerPassport: 'Passport',
  status: 'Status',
  dealNo: 'Deal No',
  bookingRate: 'Booking Rate',
  actions: 'Actions',
  rejectionReason: 'Rejection Reason',
} as const;

export const DEAL_COVER_STATUS_OPTIONS = [
  { value: 'ALL', label: 'All' },
  { value: DealCoverStatus.PENDING, label: 'Pending' },
  { value: DealCoverStatus.APPROVED, label: 'Approved' },
  { value: DealCoverStatus.REJECTED, label: 'Rejected' },
  { value: DealCoverStatus.CANCELLED, label: 'Cancelled' },
] as const;

export const DEAL_COVER_PARTY_TYPE_OPTIONS = [
  { value: 'CORPORATE_CLIENT', label: 'Corporate Client' },
  { value: 'FFMC', label: 'FFMC' },
  { value: 'RF', label: 'RF' },
  { value: 'AUTHORISED_DEALER', label: 'Authorised Dealer' },
  { value: 'RMC', label: 'RMC' },
  { value: 'FRANCHISE', label: 'Franchise' },
  { value: 'MISC_PROFILE', label: 'Misc Profile' },
] as const;
