import * as yup from 'yup';

export const productProfileSchema = yup.object({
  productCode: yup.string().trim().required('Product Code is required'),
  productDescription: yup
    .string()
    .trim()
    .required('Product Description is required'),
  acOfIssuer: yup.string().trim().default('').defined(),
  commissionAc: yup.string().trim().default('').defined(),
  fakeAccount: yup.string().trim().default('').defined(),
  bulkPurAc: yup.string().trim().default('').defined(),
  openAc: yup.string().trim().default('').defined(),
  closingAc: yup.string().trim().default('').defined(),
  expenseAc: yup.string().trim().default('').defined(),
  bulkSaleAc: yup.string().trim().default('').defined(),
  purchaseAc: yup.string().trim().default('').defined(),
  saleAc: yup.string().trim().default('').defined(),
  profitAc: yup.string().trim().default('').defined(),
  bulkProficAc: yup.string().trim().default('').defined(),
  purchaseRetCancAc: yup.string().trim().default('').defined(),
  purchaseBlkCancAc: yup.string().trim().default('').defined(),
  saleRetCancAc: yup.string().trim().default('').defined(),
  saleBlkCancAc: yup.string().trim().default('').defined(),
  branchPurAc: yup.string().trim().default('').defined(),
  branchSaleAc: yup.string().trim().default('').defined(),
  profitAcBrnSale: yup.string().trim().default('').defined(),
  retail: yup.string().trim().default('').defined(),
  bulkFee: yup.string().trim().default('').defined(),
  commLimit: yup.string().trim().default('').defined(),
  maxAmtComm: yup.string().trim().default('').defined(),
  allowFractionInFEAmount: yup.boolean().default(false),
  separateSettlementForEachInstrument: yup.boolean().default(false),
  pickSaleRateAvgAsSettlementRate: yup.boolean().default(false),
  reload: yup.boolean().default(false),
  automateSettlementRate: yup.boolean().default(false),
  isActiveProduct: yup.boolean().default(false),
  splitAndStoreBlankStockReceived: yup.boolean().default(false),
  productRequiresSettlement: yup.boolean().default(false),
  levelPriority: yup.string().trim().required('Level / Priority is required'),
  passAutoReceiptOfStockWhenSold: yup.boolean().default(false),
  reversalEffectOfProfits: yup.boolean().default(false),
  allowChangingDenominationInSales: yup.boolean().default(false),
  allowMulticard: yup.boolean().default(false),
  askReference: yup.boolean().default(false),
});
