export const DEAL_COVER_ACK_TEXT = {
  title: 'Deal Cover Acknowledgement',
  description:
    'Review pending deal cover rates by currency, then approve or reject.',
  empty: 'No deals pending acknowledgement.',
  approve: 'Approve Selected',
  reject: 'Reject Selected',
  close: 'Close',
  confirm: 'Confirm',
  back: 'Back',
  select: 'Select',
  selected: 'Selected',
  selectAll: 'Select All',
  clearSelection: 'Clear',
  dealNo: 'Deal No',
  bookingRate: 'Booking Rate',
  dealRate: 'Deal Rate',
  feAmount: 'FE Amount',
  inrAmount: 'INR Amount',
  branch: 'Branch',
  issuer: 'Issuer',
  passenger: 'Passenger',
  status: 'Status',
  currencyGroup: 'Currency',
  groupTotalFe: 'Total FE',
  groupAvgRate: 'Avg Deal Rate',
  groupTotalInr: 'Total INR',
  rejectReason: 'Rejection Reason',
  rejectReasonRequired: 'Rejection reason is required.',
  dealNoRequired: 'Deal number is required for each selected deal.',
  bookingRateRequired: 'Booking rate is required for each selected deal.',
  approved: 'Selected deals approved.',
  rejected: 'Selected deals rejected.',
  noneSelected: 'Select at least one deal.',
  incompleteRows: 'Enter deal number and booking rate for every selected deal.',
  view: 'View',
} as const;
