export const TT_SETTLEMENT_TEXT = {
  title: 'TT Settlement',
  description: 'Create and review TT branch and issuer settlements.',
  empty: 'No TT settlements found.',
  emptyUnsettled:
    'No unsettled TT items match the selected issuer, currency, and HO branch.',
  createTitle: 'Create TT Settlement',
  createDescription:
    'Select issuer and currency, then choose unsettled TT deals and enter rates.',
  editTitle: 'TT Settlement',
  readonlyDescription: 'This settlement is read-only.',
  pendingHoDescription: 'Review the settlement, then accept or reject.',
  newSettlement: 'New Settlement',
  selectItems: 'Select TT Items',
  rate: 'Rate',
  amount: 'Amount',
  type: 'Type',
  issuer: 'Issuer',
  currency: 'Currency',
  selectIssuer: 'Select issuer',
  selectCurrency: 'Select currency',
  sellingBranch: 'Selling Branch',
  hoBranch: 'HO Branch',
  selectHoBranch: 'Select HO branch',
  hoBranchRequired: 'HO branch is required',
  transactionDate: 'Transaction Date',
  transactionNumber: 'Transaction Number',
  transactionNumberPlaceholder: 'Generated on submit',
  reference: 'Reference',
  remarks: 'Remarks',
  dealNo: 'Deal No',
  feAmount: 'FE Amount',
  dealRate: 'Deal Rate',
  bookingRate: 'Booking Rate',
  itemsHeading: 'Settlement Items',
  detailsHeading: 'Settlement Details',
  submit: 'Submit Settlement',
  accept: 'Accept',
  reject: 'Reject',
  cancel: 'Cancel Settlement',
  back: 'Back',
  close: 'Close',
  confirm: 'Confirm',
  select: 'Select',
  selected: 'Selected',
  apply: 'Apply',
  rejectReason: 'Rejection Reason',
  cancelReason: 'Cancellation Reason',
  kindBranch: 'Branch to HO',
  kindIssuer: 'HO to Issuer',
  view: 'View',
  editReview: 'Edit / Review',
  created: 'TT settlement created.',
  accepted: 'TT settlement accepted.',
  rejected: 'TT settlement rejected.',
  cancelled: 'TT settlement cancelled.',
  rejectReasonRequired: 'Rejection reason is required.',
  cancelReasonRequired: 'Cancellation reason is required.',
  notFound: 'TT settlement not found.',
  itemsCount: 'Items',
  status: 'Status',
  actions: 'Actions',
} as const;

export const TT_SETTLEMENT_STATUS_OPTIONS = [
  { value: 'ALL', label: 'All' },
  { value: 'PENDING_HO_ACCEPTANCE', label: 'Pending HO Acceptance' },
  { value: 'ACCEPTED', label: 'Accepted' },
  { value: 'ISSUER_SETTLED', label: 'Issuer Settled' },
  { value: 'REJECTED', label: 'Rejected' },
  { value: 'CANCELLED', label: 'Cancelled' },
] as const;
