export const CARD_SETTLEMENT_REPORT_TEXT = {
  unsettledTitle: 'Unsettled CARD Report',
  unsettledDescription:
    'CARD sales in the selected period that were not yet branch-HO settled as of the period end, grouped by selling branch.',
  settledTitle: 'Settled CARD Report',
  settledDescription:
    'CARD series whose branch-HO settlement transaction date falls in the selected period. Sale values are the original sale even when the sale date is outside the period.',
  reportViewTitle: 'Report View',
  reportViewDescription:
    'Rows are grouped by selling branch. Group totals use stored quantity and amount values.',
  download: 'Download',
  reset: 'Reset',
  viewReport: 'View Report',
  loadError: 'Failed to load report data. Please try again.',
  xlsx: 'XLSX',
  csv: 'CSV',
  appliedPrefix: 'Applied',
  all: 'All',
  sortBy: 'Sort By',
  dateAsc: 'Date Asc',
  dateDesc: 'Date Desc',
  branchHeading: 'Branch',
  productHeading: 'CARD Product',
  currencyHeading: 'Currency',
  issuerHeading: 'Issuer',
  branchEmpty: 'No branch options available.',
  productEmpty: 'No CARD product options available.',
  currencyEmpty: 'No currency options available.',
  issuerEmpty: 'No issuer options available.',
  loadingOptions: 'Loading options...',
  noOptions: 'No options available',
  selectedOf: (count: number, total: number) => `${count} of ${total} selected`,
} as const;
