import type { ICreateProductProfile, IProductProfile } from '../types';

export const createEmptyProductProfileFormValues =
  (): ICreateProductProfile => ({
    productCode: '',
    productDescription: '',
    acOfIssuer: '',
    commissionAc: '',
    fakeAccount: '',
    bulkPurAc: '',
    openAc: '',
    closingAc: '',
    expenseAc: '',
    bulkSaleAc: '',
    purchaseAc: '',
    saleAc: '',
    profitAc: '',
    bulkProficAc: '',
    purchaseRetCancAc: '',
    purchaseBlkCancAc: '',
    saleRetCancAc: '',
    saleBlkCancAc: '',
    branchPurAc: '',
    branchSaleAc: '',
    profitAcBrnSale: '',
    retail: '',
    bulkFee: '',
    commLimit: '',
    maxAmtComm: '',
    allowFractionInFEAmount: false,
    separateSettlementForEachInstrument: false,
    pickSaleRateAvgAsSettlementRate: false,
    reload: false,
    automateSettlementRate: false,
    isActiveProduct: false,
    splitAndStoreBlankStockReceived: false,
    productRequiresSettlement: false,
    levelPriority: '',
    passAutoReceiptOfStockWhenSold: false,
    reversalEffectOfProfits: false,
    allowChangingDenominationInSales: false,
    allowMulticard: false,
    askReference: false,
    availableInRetailBuying: false,
    retailBuyingSeriesApplicable: false,
    availableInRetailSelling: false,
    retailSellingSeriesApplicable: false,
    availableInBulkBuying: false,
    bulkBuyingSeriesApplicable: false,
    availableInBulkSelling: false,
    bulkSellingSeriesApplicable: false,
    allowProductCancellation: false,
    maintainBlankStockOfProduct: false,
    denominationApplicable: false,
    allowAddOnLinking: false,
    instrumentIssuingAuthorityRequired: false,
  });

export const mapRecordToFormValues = (
  record: IProductProfile
): ICreateProductProfile => ({
  productCode: record.productCode,
  productDescription: record.productDescription,
  acOfIssuer: record.acOfIssuer,
  commissionAc: record.commissionAc,
  fakeAccount: record.fakeAccount,
  bulkPurAc: record.bulkPurAc,
  openAc: record.openAc,
  closingAc: record.closingAc,
  expenseAc: record.expenseAc,
  bulkSaleAc: record.bulkSaleAc,
  purchaseAc: record.purchaseAc,
  saleAc: record.saleAc,
  profitAc: record.profitAc,
  bulkProficAc: record.bulkProficAc,
  purchaseRetCancAc: record.purchaseRetCancAc,
  purchaseBlkCancAc: record.purchaseBlkCancAc,
  saleRetCancAc: record.saleRetCancAc,
  saleBlkCancAc: record.saleBlkCancAc,
  branchPurAc: record.branchPurAc,
  branchSaleAc: record.branchSaleAc,
  profitAcBrnSale: record.profitAcBrnSale,
  retail: record.retail,
  bulkFee: record.bulkFee,
  commLimit: record.commLimit,
  maxAmtComm: record.maxAmtComm,
  allowFractionInFEAmount: record.allowFractionInFEAmount,
  separateSettlementForEachInstrument:
    record.separateSettlementForEachInstrument,
  pickSaleRateAvgAsSettlementRate: record.pickSaleRateAvgAsSettlementRate,
  reload: record.reload,
  automateSettlementRate: record.automateSettlementRate,
  isActiveProduct: record.isActiveProduct,
  splitAndStoreBlankStockReceived: record.splitAndStoreBlankStockReceived,
  productRequiresSettlement: record.productRequiresSettlement,
  levelPriority: record.levelPriority,
  passAutoReceiptOfStockWhenSold: record.passAutoReceiptOfStockWhenSold,
  reversalEffectOfProfits: record.reversalEffectOfProfits,
  allowChangingDenominationInSales: record.allowChangingDenominationInSales,
  allowMulticard: record.allowMulticard,
  askReference: record.askReference,
  availableInRetailBuying: record.availableInRetailBuying,
  retailBuyingSeriesApplicable: record.retailBuyingSeriesApplicable,
  availableInRetailSelling: record.availableInRetailSelling,
  retailSellingSeriesApplicable: record.retailSellingSeriesApplicable,
  availableInBulkBuying: record.availableInBulkBuying,
  bulkBuyingSeriesApplicable: record.bulkBuyingSeriesApplicable,
  availableInBulkSelling: record.availableInBulkSelling,
  bulkSellingSeriesApplicable: record.bulkSellingSeriesApplicable,
  allowProductCancellation: record.allowProductCancellation,
  maintainBlankStockOfProduct: record.maintainBlankStockOfProduct,
  denominationApplicable: record.denominationApplicable,
  allowAddOnLinking: record.allowAddOnLinking,
  instrumentIssuingAuthorityRequired: record.instrumentIssuingAuthorityRequired,
});

export const mapFormValuesToRecord = (
  values: ICreateProductProfile,
  id: string,
  createdAt: string,
  updatedAt: string
): IProductProfile => ({
  id,
  createdAt,
  updatedAt,
  ...values,
});
