import type {
  ProductProfileFormValues,
  ProductProfileRecord,
} from '../types';

export const createEmptyProductProfileFormValues =
  (): ProductProfileFormValues => ({
    productCode: '',
    productDescription: '',
    acOfIssuer: '',
    commissionAc: '',
    fakeAccount: '',
    bulkPurAc: '',
    openAc: '',
    closingAc: '',
    expenseAc: '',
    bulkSaleAc: '',
    purchaseAc: '',
    saleAc: '',
    profitAc: '',
    bulkProficAc: '',
    purchaseRetCancAc: '',
    purchaseBlkCancAc: '',
    saleRetCancAc: '',
    saleBlkCancAc: '',
    branchPurAc: '',
    branchSaleAc: '',
    profitAcBrnSale: '',
    retail: '',
    bulkFee: '',
    commLimit: '',
    maxAmtComm: '',
    allowFractionInFEAmount: false,
    separateSettlementForEachInstrument: false,
    pickSaleRateAvgAsSettlementRate: false,
    reload: false,
    automateSettlementRate: false,
    isActiveProduct: false,
    splitAndStoreBlankStockReceived: false,
    productRequiresSettlement: false,
    levelPriority: '',
    passAutoReceiptOfStockWhenSold: false,
    reversalEffectOfProfits: false,
    allowChangingDenominationInSales: false,
    allowMulticard: false,
    askReference: false,
  });

export const mapRecordToFormValues = (
  record: ProductProfileRecord
): ProductProfileFormValues => ({
  productCode: record.productCode,
  productDescription: record.productDescription,
  acOfIssuer: record.acOfIssuer,
  commissionAc: record.commissionAc,
  fakeAccount: record.fakeAccount,
  bulkPurAc: record.bulkPurAc,
  openAc: record.openAc,
  closingAc: record.closingAc,
  expenseAc: record.expenseAc,
  bulkSaleAc: record.bulkSaleAc,
  purchaseAc: record.purchaseAc,
  saleAc: record.saleAc,
  profitAc: record.profitAc,
  bulkProficAc: record.bulkProficAc,
  purchaseRetCancAc: record.purchaseRetCancAc,
  purchaseBlkCancAc: record.purchaseBlkCancAc,
  saleRetCancAc: record.saleRetCancAc,
  saleBlkCancAc: record.saleBlkCancAc,
  branchPurAc: record.branchPurAc,
  branchSaleAc: record.branchSaleAc,
  profitAcBrnSale: record.profitAcBrnSale,
  retail: record.retail,
  bulkFee: record.bulkFee,
  commLimit: record.commLimit,
  maxAmtComm: record.maxAmtComm,
  allowFractionInFEAmount: record.allowFractionInFEAmount,
  separateSettlementForEachInstrument:
    record.separateSettlementForEachInstrument,
  pickSaleRateAvgAsSettlementRate: record.pickSaleRateAvgAsSettlementRate,
  reload: record.reload,
  automateSettlementRate: record.automateSettlementRate,
  isActiveProduct: record.isActiveProduct,
  splitAndStoreBlankStockReceived: record.splitAndStoreBlankStockReceived,
  productRequiresSettlement: record.productRequiresSettlement,
  levelPriority: record.levelPriority,
  passAutoReceiptOfStockWhenSold: record.passAutoReceiptOfStockWhenSold,
  reversalEffectOfProfits: record.reversalEffectOfProfits,
  allowChangingDenominationInSales: record.allowChangingDenominationInSales,
  allowMulticard: record.allowMulticard,
  askReference: record.askReference,
});

export const mapFormValuesToRecord = (
  values: ProductProfileFormValues,
  id: string,
  createdAt: string,
  updatedAt: string
): ProductProfileRecord => ({
  id,
  createdAt,
  updatedAt,
  ...values,
});
