import type { ICreateAccountProfile } from '../types/accountProfileTypes';

export const createEmptyAccountProfileFormValues = (): ICreateAccountProfile => ({
  divisionDept: '',
  accountCode: '',
  accountName: '',
  accountType: '',
  subLedger: '',
  bankNature: '',
  currencyId: '',
  financialCodeId: '',
  financialSubProfileId: '',
  pettyCashExpenseId: '',
  zeroBalanceAtEod: false,
  branchIdToTransfer: '',
  mapToAccountId: '',
  retailSale: false,
  retailPurchase: false,
  bulkSale: false,
  bulkPurchase: false,
  expense: false,
  receipt: false,
  payment: false,
  journalVoucher: false,
  active: true,
  cmsBank: false,
  directRemittance: false,
});
