export const PRODUCT_SETTLEMENT_TEXT = {
  title: 'Product Settlement',
  description:
    'Create and review CARD and TT branch and issuer settlements.',
  empty: 'No product settlements found.',
  emptyUnsettled:
    'No unsettled items match the selected issuer, currency, and HO branch.',
  createTitle: 'Create Product Settlement',
  createDescription:
    'Select issuer and currency, then choose unsettled CARD or TT items and enter rates.',
  editTitle: 'Product Settlement',
  readonlyDescription: 'This settlement is read-only.',
  pendingHoDescription: 'Review the settlement, then accept or reject.',
  newSettlement: 'New Settlement',
  selectItems: 'Select Items',
  saleKind: 'Sale Kind',
  rate: 'Rate',
  amount: 'Amount',
  type: 'Type',
  settlementType: 'Settlement Type',
  productCode: 'Product Code',
  issuer: 'Issuer',
  currency: 'Currency',
  selectIssuer: 'Select issuer',
  selectCurrency: 'Select currency',
  sellingBranch: 'Selling Branch',
  hoBranch: 'HO Branch',
  selectHoBranch: 'Select HO branch',
  hoBranchRequired: 'HO branch is required',
  allBranches: 'All branches',
  transactionDate: 'Transaction Date',
  transactionNumber: 'Transaction Number',
  transactionNumberPlaceholder: 'Generated on submit',
  reference: 'Reference',
  remarks: 'Remarks',
  cardNumber: 'Card Number',
  series: 'Series',
  kitNumber: 'Kit Number',
  denomination: 'Denomination',
  bookingRate: 'Booking Rate',
  itemsHeading: 'Settlement Items',
  detailsHeading: 'Settlement Details',
  submit: 'Submit Settlement',
  accept: 'Accept',
  reject: 'Reject',
  cancel: 'Cancel Settlement',
  back: 'Back',
  close: 'Close',
  confirm: 'Confirm',
  select: 'Select',
  selected: 'Selected',
  apply: 'Apply',
  rejectReason: 'Rejection Reason',
  cancelReason: 'Cancellation Reason',
  kindBranch: 'Branch to HO',
  kindIssuer: 'HO to Issuer',
  view: 'View',
  editReview: 'Edit / Review',
  created: 'Product settlement created.',
  accepted: 'Product settlement accepted.',
  rejected: 'Product settlement rejected.',
  cancelled: 'Product settlement cancelled.',
  rejectReasonRequired: 'Rejection reason is required.',
  cancelReasonRequired: 'Cancellation reason is required.',
  notFound: 'Product settlement not found.',
  itemsCount: 'Items',
  status: 'Status',
  actions: 'Actions',
  typeCard: 'CARD',
  typeTt: 'TT',
} as const;

export const PRODUCT_SETTLEMENT_STATUS_OPTIONS = [
  { value: 'ALL', label: 'All' },
  { value: 'PENDING_HO_ACCEPTANCE', label: 'Pending HO Acceptance' },
  { value: 'ACCEPTED', label: 'Accepted' },
  { value: 'ISSUER_SETTLED', label: 'Issuer Settled' },
  { value: 'REJECTED', label: 'Rejected' },
  { value: 'CANCELLED', label: 'Cancelled' },
] as const;
